### PR TITLE
Updated Readme.md file extensively

### PR DESCRIPTION
**Pull request by gitgoap**
# Issue: #94 
# Changes Made

1. Updated the screenshots of all the web pages present in the readme file.

2. Added **Discord** button 

3. Added **Tech Stack Used** section

4. Updated **contributing** section extensively for beginners including creating a section for a detailed step-by-step process of creating a **Pull Request**

5. Added some relevant images and updated the **table of content**.

### CODE REVIEW

**Comment by gitgoap** [comment]
@Spandan-Bhattacharya 

This took a hell lot of effort and a lot of time, I think it should be labelled as **medium** not **easy**.
Since it required some research on how to write a readme file for **beginners**.

**Comment by Spandan-Bhattacharya** [comment]
Is the Workflow required in the main repo?

**Comment by gitgoap** [comment]
> Is the Workflow required in the main repo?

It's not required.

**Comment by Spandan-Bhattacharya** [comment]
This is great!, can you just add something about how to use the said workflow?
I assume its for people who fork the repo, to keep their repo updated.

**Comment by gitgoap** [comment]
> This is great!, can you just add something about how to use the said workflow?
> I assume its for people who fork the repo, to keep their repo updated.

Okay

**Comment by Spandan-Bhattacharya** [comment]
Any updates?
@gitgoap

**Comment by gitgoap** [comment]
> Any updates?
> @gitgoap 

I now feel workflow could be little advance of beginners as this repo is targeted for beginners.
You should remove the yaml file.

**Comment by Spandan-Bhattacharya** [comment]
Okay then remove it and commit

**Review by gitgoap — COMMENTED** [review]
Deleted Yaml file

**Pull request merged**
