### PR TITLE
Improved 8x8 suduku solver

### PR DESCRIPTION
**Pull request by Surajit0573**
Title : Improve the 8x8 solver.
Issue : #217
Changes : 
1. Font changed as 4x4 solver.
2. Solve animation added as 9x9 solver.
3. Fixed reset coloring issue.

Improved version : 

[screen-capture.webm](https://github.com/Spandan-Bhattacharya/Solve_it/assets/111490250/65697fe5-ada8-4832-8ea3-1117c5718aa8)

### CODE REVIEW

**Comment by Spandan-Bhattacharya** [comment]
Everything is good!
Just make the solver responsive. 
Then I will merge the PR

**Comment by Surajit0573** [comment]
@Spandan-Bhattacharya ,Can you please explain a little what to do !!

**Comment by Spandan-Bhattacharya** [comment]
Just make the solver look suitable for mobile screens.
https://www.w3schools.com/html/html_responsive.asp

**Comment by Surajit0573** [comment]
@Spandan-Bhattacharya , Done...

image

image

**Pull request merged**
