### PR TITLE
Sudoku-solver-4x4: Invalid input alert. #7

### PR DESCRIPTION
**Pull request by Prithwi32**
1) Now when an invalid input is given, a message is displayed inside html of the website itself, without using the "alert" function.
2) The grid gets reset, after the message is shown, thus allowing the user to re-enter the values without refreshing the page.
Both these cases were solved..

### CODE REVIEW

**Comment by Prithwi32** [comment]
@Spandan-Bhattacharya  Please could you review this and let me know the feedback

**Comment by Prithwi32** [comment]
> Can you give some screenshot of it in action?

sure

**Comment by Prithwi32** [comment]
> Can you give some screenshot of it in action?



https://github.com/Spandan-Bhattacharya/Solve_it/assets/115262737/c7011184-ffb3-4213-b0f3-f8478c71273e

@Spandan-Bhattacharya check this video

**Comment by Spandan-Bhattacharya** [comment]
Yeah the alert is good, but for the reset part, make sure that the whole grid is reset, not just the last input character.

**Comment by Prithwi32** [comment]
> Yeah the alert is good, but for the reset part, make sure that the whole grid is reset, not just the last input character.

@Spandan-Bhattacharya I can but resetting whole grid is made as another issue(#5) ...so I implemented this...What shoud I do?

**Comment by Spandan-Bhattacharya** [comment]
Okay i see, then it's fine.
Good Job!

**Comment by Prithwi32** [comment]
> Okay i see, then it's fine. Good Job!

Thank You !

**Comment by Spandan-Bhattacharya** [comment]
Merged! Good Job!

**Pull request merged**
