### PR TITLE
Footer added with some changes

### PR DESCRIPTION
**Pull request by debuuuu007**
I have added the footer in all three pages, also rectified the code base. Just do check once from your side too.

And as i have mentioned if possible give this problem a hard tag.

Thank you.

### CODE REVIEW

**Comment by Spandan-Bhattacharya** [comment]
Can the red hue be changed to something else?

**Comment by debuuuu007** [comment]
Which red hue ? Can you elaborate it where is the issue ?

**Comment by Spandan-Bhattacharya** [comment]
The linear gradient with the colour on the bottom right.

**Comment by debuuuu007** [comment]
Ok i am changing it wait.

**Pull request closed without merging**
