### PR TITLE
suggestion section created

### PR DESCRIPTION
**Pull request by Komal73**
created a suggestion section for users to suggest their favorite puzzles through email

### CODE REVIEW

**Comment by Komal73** [comment]
@Spandan-Bhattacharya kindly check this PR

**Comment by Spandan-Bhattacharya** [comment]
can you share a video of the pull request in action? It looks very different than the one you showed a little bit ago.

**Comment by Komal73** [comment]
yes just added some transition.


https://github.com/Spandan-Bhattacharya/Solve_it/assets/115211296/97258e7d-dbde-4a44-bd0c-17c1bda0b0c3

**Comment by Spandan-Bhattacharya** [comment]
I think the rainbow effect in not going with the theme of the page.
Also, the whole page code has changed with the PR.
Can you create a new branch where only the suggestion section is added, and everything else is the same?
Otherwise it cannot be merged correctly.

**Comment by Komal73** [comment]
okay

**Pull request closed without merging**
