### PR TITLE
Improved Search function and UI

### PR DESCRIPTION
**Pull request by Surajit0573**
Title : Improve Search function & UI 
issue : #300
changes : 
- Improved Search bar 
- Improved UI of contact page

### CODE REVIEW

**Comment by Spandan-Bhattacharya** [comment]
For the contact page, the new writing looks better.
But, keep the old footer.

Also, its good that you have added the games to the search list. Can you make it so that strings can be searched as well.
Like if we search for "sudoku".
It would show the 4 sudoku games and the 4 solvers in the results.

**Comment by Surajit0573** [comment]
> For the contact page, the new writing looks better. But, keep the old footer.
> 
> Also, its good that you have added the games to the search list. Can you make it so that strings can be searched as well. Like if we search for "sudoku". It would show the 4 sudoku games and the 4 solvers in the results.

@Spandan-Bhattacharya, I changed the footer and the search function as asked.

**Comment by Spandan-Bhattacharya** [comment]
The hamburger for the contact page is not working. Otherwise it is good.

**Comment by Surajit0573** [comment]
> The hamburger for the contact page is not working. Otherwise it is good.

@Spandan-Bhattacharya, I fixed the Hamburger menu.

**Pull request merged**
