### PR TITLE
Redesigned the Gototop button

### PR DESCRIPTION
**Pull request by debuuuu007**
I have redesigned the button, also previously contact and about page was not linked with this button, i have linked that too.

Thank you.

### CODE REVIEW

**Comment by Spandan-Bhattacharya** [comment]
It's good, but currently the button stays black for only the 1st time it's click.
I guess that is not intended behaviour.
So if it remains blue while on hover and while in action(the time when the upscroll happens) and black in other times, it would be better i think.

**Comment by debuuuu007** [comment]
https://github.com/Spandan-Bhattacharya/Solve_it/assets/121102183/264d2695-ca53-4985-a7d3-82a313343754

Can you describe the problem relating with the video given

**Comment by Spandan-Bhattacharya** [comment]
The error is not present in the video.
I think then this is good.
No need to change anything

**Comment by Spandan-Bhattacharya** [comment]
Merged!

**Pull request merged**
