### PR TITLE
Search bar fixed

### PR DESCRIPTION
**Pull request by GhoshAditi**
Issue #68 
made the search bar visible

before
Untitle423d

after
Untitledsearch

### CODE REVIEW

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya plz check

**Comment by Spandan-Bhattacharya** [comment]
Can the bar be made such that it's opacity decreases when it's selected?
The black border is not looking too good with it's surroundings, i think.

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya  i can remove the border.

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya 
image

is this one better?

**Comment by Spandan-Bhattacharya** [comment]
I think it doesn't need a border. It should span the entire Nav Bar.

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya 
image
this one?

**Comment by Spandan-Bhattacharya** [comment]
Yeah now make the field more transparent

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya 
image
this?

**Comment by Spandan-Bhattacharya** [comment]
No i meant for the input field, which is a rectangular box, spanning the full navbar height and some width.

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya there's no recatangular box anymore. iremoved the thing

**Comment by Spandan-Bhattacharya** [comment]
Then we have to bring it back😂

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya u want the rectangular box with less opacity?

**Comment by Spandan-Bhattacharya** [comment]
yes, when the input field is selected for input

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya 
image
this?

**Comment by Spandan-Bhattacharya** [comment]
wait i am sending some reference

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya just making the search solver a little darker that way ig it would feel good

**Comment by Spandan-Bhattacharya** [comment]
you mean the writing?

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya yeah

**Comment by Spandan-Bhattacharya** [comment]
The search bar would be like this when it is selected for giving input.
It can stay the same in other times

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya 
image
i think this one matches

**Comment by Spandan-Bhattacharya** [comment]
make the whole box, not just the outline have less opacity

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya  i have synced the changes. hope it matches what you want.

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya the whole box has transparent colour. its due to the background. the background image of the site is of that colour. the box has no extra colour. it only has an outline and nothing else. you can check. its the background colour.

**Comment by Spandan-Bhattacharya** [comment]
Okay, I think i know the issue here.
I meant making the input field look like it is see through, like one can see behind the navbar(in a clouded manner).
I will give an actual design tomorrow.

**Comment by Spandan-Bhattacharya** [comment]
> @Spandan-Bhattacharya the whole box has transparent colour. its due to the background. the background image of the site is of that colour. the box has no extra colour. it only has an outline and nothing else. you can check. its the background colour.

Yes i understand that.

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya what about this one?

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya 
image
this is how it looks when selected.
image
looks like this when not selected.

**Comment by Spandan-Bhattacharya** [comment]
Okay, This is unfortunately not what i am looking for, I will send you a design tomorrow.

**Comment by Spandan-Bhattacharya** [comment]
And thank you for not getting irritated at this

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya no no its ok. :)
yeah plz send me the reference tomorrow.

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya can u send me the reference picture?

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya will u provide me a reference picture plz ?

**Comment by Spandan-Bhattacharya** [comment]
Yeah sorry i got a little busy, will send it shortly

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya hope the recent commit is what you were looking for

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya tbh i have spent quite some time as well as my energy doing this. can u plz label me as medium?plz? :)

**Pull request merged**
