### PR TITLE
Add UNO game #283

### LINKED ISSUE #283: Add UNO game
Add uno game 

UNO

### PR DESCRIPTION
**Pull request by AftabMankapure**
Add UNO game #283
Issue #283 
close #283

### CODE REVIEW

**Comment by Spandan-Bhattacharya** [comment]
The card in the home page of the solve it site is not showing up correctly, sob div tag issue.

**Comment by Spandan-Bhattacharya** [comment]
Make it responsive and I will merge the PR.

**Comment by Spandan-Bhattacharya** [comment]
The link in the readme redirects to another project of JWoC.

**Comment by AftabMankapure** [comment]
UNO

newUNO

**Comment by Spandan-Bhattacharya** [comment]
It's not showing up correctly in mobile phones.

**Comment by AftabMankapure** [comment]
iphone XR


s8

check it

**Pull request merged**
