### PR TITLE
Revamped the home screen solver cards

### PR DESCRIPTION
**Pull request by GhoshAditi**
Issue #50

@Spandan-Bhattacharya I have changed the style of the solver cards. plz check

Screenshot 
done

### CODE REVIEW

**Comment by Spandan-Bhattacharya** [comment]
Really Impressive!
I see that you have implemented the sudoku picture in the background in the code, but it is somehow not showing up in the preview.

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya its showing in my laptop. can u plz try reloading the page once? else i would try once again to fix the issue.

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya is it showing now?

**Comment by Spandan-Bhattacharya** [comment]
No still not showing

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya ok . trying to fix the issue

**Comment by Spandan-Bhattacharya** [comment]
Yeah, I am also trying to figure out the problem

**Comment by GhoshAditi** [comment]
> Yeah, I am also trying to figure out the problem

yeah thanks. me too. probably i would be able to fix it tomorrow. sorry for the inconvenience faced.

**Comment by Spandan-Bhattacharya** [comment]
No problem, i was 90% sure people won't be able to copy the design well, but you have done very good!
Now, 1 tiny thing, the gradient type would be diagonal.

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya  thanks. Ok tomorrow I would fix everything 😊😊😊.

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya can u now view the background image? plz confirm.

**Comment by Spandan-Bhattacharya** [comment]
No Still not visible, but i am accepting the PR

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya thanks. but at the same time kinda sorry because of the inconvenience.

**Pull request merged**
