### PR TITLE
Added the search bar

### PR DESCRIPTION
**Pull request by shrutisk0405**
Created an auto-completing search bar for the solver which will suggest the available solver on the page that a user is finding.

### CODE REVIEW

**Comment by shrutisk0405** [comment]
Please see the pull request. Suggest if any modification is needed.
Thank you

**Comment by Spandan-Bhattacharya** [comment]
Can you please attach some screenshots or screen recording of it working?

**Comment by shrutisk0405** [comment]
yes,sure.

solver1

https://github.com/Spandan-Bhattacharya/Solve_it/assets/121231756/0408e4ca-eba5-42c2-8fa1-bf7c791f867b


arya/Solve_it/assets/121231756/5ee0d4c0-a5ab-4e05-8a87-c4bdb375aa8c)
solver3

**Comment by Spandan-Bhattacharya** [comment]
Looks great! Can you copy the things you added to another file, like a notepad or something and then sync your fork to the latest. Then again paste the additions and commit?

**Comment by Spandan-Bhattacharya** [comment]
Also please check the linking of the css sheet to the pages.
When I see the preview, the search bar is not showing like your screenshots.

**Comment by shrutisk0405** [comment]
should I add all the code to one file(nodepad) or make individual files for html, css and js?

**Comment by Spandan-Bhattacharya** [comment]
Yeah it's as per your convenience.
As when you sync, all your changes are lost.

So if you copy it elsewhere and then sync and then again paste it accordingly. Your changes won't be lost this way and syncing won't be a hassle.

**Comment by shrutisk0405** [comment]
Should i discard the commits and commit again.and also do i need to add other index file since it is showing a conflict in the branch

**Comment by shrutisk0405** [comment]
I have made the search bar responsive now .

**Pull request merged**
