### PR TITLE
Improved the Footer of the Original Website.

### PR DESCRIPTION
**Pull request by SohanRC**
Improved the Footer of the Original Website. Also added some hover effects to make the website beautiful. I am attaching the Screenshot below. Issue No = **#100**

Screenshot 2024-01-25 003809

### CODE REVIEW

**Comment by Spandan-Bhattacharya** [comment]
This is good, but can you make the solve it writing in some other font?
And i know i told to use that colour for the writings, but try using some other colours with it too, for the text.

**Comment by SohanRC** [comment]
> This is good, but can you make the solve it writing in some other font? And i know i told to use that colour for the writings, but try using some other colours with it too, for the text.

Okay i am doing it

**Comment by Spandan-Bhattacharya** [comment]
Okay!

**Comment by Spandan-Bhattacharya** [comment]
Sync your repo to the main, as some major changes were done to the page.

**Comment by SohanRC** [comment]
@ Is this Okay ?

Screenshot 2024-01-25 033245

**Pull request closed without merging**
