### PR TITLE
Added customised scrollbar

### PR DESCRIPTION
**Pull request by Sneha123-zudo**
I had added the customised scrollbar to all the pages of games , pleas echeck my pull request

### CODE REVIEW

**Comment by Sneha123-zudo** [comment]
Please check and merge my pull request

**Comment by Spandan-Bhattacharya** [comment]
Sudoku 4x4 game seems broken

**Comment by Sneha123-zudo** [comment]
I had fixed that

**Comment by Spandan-Bhattacharya** [comment]
It is not showing up correctly in my screen.

**Comment by Sneha123-zudo** [comment]
Can i close this pr and create a new one??

**Comment by Spandan-Bhattacharya** [comment]
Yes

**Pull request closed without merging**
