### PR TITLE
[ISSUE - 133] Enhance Search Box in the Navbar

### LINKED ISSUE #133: UI: Enhance Search Box in the Navbar
The current Navbar Search Box requires improvements for a more enhanced look to match the theme. This enhancement aims to address visual appeal, responsiveness across devices, and modular implementation of the box

@Spandan-Bhattacharya Please assign this issue to me under JWOC.

### PR DESCRIPTION
**Pull request by antilneeraj**
# Description👨‍💻 

Enhanced the Search Box to match the theme of the website and also made some major bug fixes in the navbar.
- The Changes made are Responsive for smaller screens as well.

# Fixes Issue🛠️

- Closes #133 

# Type of change📄

- [x] UI Enhancement

# How this has been tested✅

I have done Alpha, Beta & Unit Testing

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image
image
image
image

### CODE REVIEW

**Comment by antilneeraj** [comment]
@Spandan-Bhattacharya This pull request is ready for review and merge. Additionally, I kindly request you to consider adding the `JWOC` and if possible, a `HARD` Difficulty label to this pull request as I have also fixed some major UI bugs in navbar to enhance its appearance.

Thankyou for the opportunity to contribute to this project.

**Comment by Spandan-Bhattacharya** [comment]
Looks really good!
Just one thing,


When the search bar has something written in it, and then it is closed, the dropdown should collapse.

**Comment by antilneeraj** [comment]
Hey @Spandan-Bhattacharya, I've resolved the issue. Could you kindly review the Pull Request and share your feedback?

**Comment by Spandan-Bhattacharya** [comment]
Great Job!!

**Comment by antilneeraj** [comment]
Thankyou 😄

**Pull request merged**
