### PR TITLE
new game Word Guessing Game #284

### LINKED ISSUE #284: new game Word Guessing Game
new game Word Guessing Game #203

User can guess the word by hint

word-

### PR DESCRIPTION
**Pull request by AftabMankapure**
new game Word Guessing Game #284

issue #284 
close #284

### CODE REVIEW

**Comment by AftabMankapure** [comment]
pls check this PR

**Comment by Spandan-Bhattacharya** [comment]
The code seems to be taken from some YouTube channel in it's entirety.
Make the necessary changes and re-submit.

**Comment by Spandan-Bhattacharya** [comment]
@AftabMankapure Any updates?

**Comment by AftabMankapure** [comment]
old one 

newW


New 

newWord

**Pull request merged**
