### PR TITLE
Sudoku-Solver-4x4: Improve the visual representation. #9

### PR DESCRIPTION
**Pull request by Prithwi32**
Added style to heading, cells, grid
Added Background Image
Added button which on click redirects to home page
Centered all the elements
Stylized the buttons

### CODE REVIEW

**Comment by Spandan-Bhattacharya** [comment]
It's great!

But can you make it so that the Sudoku grid is made of colour, and the 2x2 boxes are differentiated by a thicker border between the boxes.
Like,
https://images.app.goo.gl/z29cj3wsTM34Dptg8


I think a blue background with a yellowish golden grid would work great with the overall theme of the website.

Also I think the reset button is not working correctly.
I will increase the difficulty to hard once these are implemented.

**Comment by Prithwi32** [comment]
> It's great!
> 
> But can you make it so that the Sudoku grid is made of colour, and the 2x2 boxes are differentiated by a thicker border between the boxes. Like, https://images.app.goo.gl/z29cj3wsTM34Dptg8
> 
> I think a blue background with a yellowish golden grid would work great with the overall theme of the website.
> 
> Also I think the reset button is not working correctly. I will increase the difficulty to hard once these are implemented.

@ should I change all cells color to blue background with yellowish gloden grid?
and actually reset button issue is given to other, Should I implement that too now?

**Comment by Prithwi32** [comment]
> > It's great!
> > But can you make it so that the Sudoku grid is made of colour, and the 2x2 boxes are differentiated by a thicker border between the boxes. Like, https://images.app.goo.gl/z29cj3wsTM34Dptg8
> > I think a blue background with a yellowish golden grid would work great with the overall theme of the website.
> > Also I think the reset button is not working correctly. I will increase the difficulty to hard once these are implemented.
> 
> @Spandan-Bhattacharya should I change all cells color to blue background with yellowish gloden grid? and actually reset button issue is given to other, Should I implement that too now?
> 
> s-ui

like this?

**Comment by Spandan-Bhattacharya** [comment]
Yeah make the whole grid golden.
And reset button has been implemented by another mentee. So it should work.

**Comment by Prithwi32** [comment]
s-ui

**Comment by Prithwi32** [comment]
> solve_it_ui.mp4

@Spandan-Bhattacharya Kindly check this once

**Comment by Spandan-Bhattacharya** [comment]
This is great, and i am really sorry to ask for so many revisons, but i meant that the grid with it's cells will be golden.
And the background of the page would be deep bluish, kinda like the home page.

**Comment by Prithwi32** [comment]
> This is great, and i am really sorry to ask for so many revisons, but i meant that the grid with it's cells will be golden. And the background of the page would be deep bluish, kinda like the home page.

Should I remove the background image whivh is applied now?

**Comment by Spandan-Bhattacharya** [comment]
Yeah change the background image.

**Comment by Prithwi32** [comment]
ui

**Comment by Spandan-Bhattacharya** [comment]
great job!

**Comment by Prithwi32** [comment]
> great job!

Thank You! it means lot to me :)

**Pull request merged**
