### PR TITLE
Implemented 6x6 Sudoku Solver

### LINKED ISSUE #95: Implement the 6x6 sudoku solver.
Refer to the 4x4 solver code for implementation of the solver functions of the 6x6 sudoku.
The 6x6 solver should have 3 rows, each with 2 columns.
Thus each smaller box will have a height of 2 cells and a width of 3 cells.
Like this:
image
Do not work on the CSS of the page, just implement the bare-bones solver.

### PR DESCRIPTION
**Pull request by thatguywhocode**
Closes #95 

i have successfully implemented the 6x6 Sudoku Solver.

### CODE REVIEW

**Comment by Spandan-Bhattacharya** [comment]
Okay this is good, but can you sync your fork to the current version of the site?
And the implementation is great, but the invalid input is not working, check the 4x4 solver for that.

**Comment by thatguywhocode** [comment]
okay , i will check that

**Comment by thatguywhocode** [comment]
Can you please elaborate invalid input

**Comment by Spandan-Bhattacharya** [comment]
Right now, the input is invalid if the same number is present in both the same row column or box.

**Comment by thatguywhocode** [comment]
but @Spandan-Bhattacharya , how can same number be in same row column or box, in sudoku, the number should be unique?

**Comment by Spandan-Bhattacharya** [comment]
Yeah it can't be.
Thus, if the user gives in the input, an input where that is not maintained, we call it invalid, as no solution can be made.
In other words, if the input sudoku has no solution, its invalid.

**Comment by thatguywhocode** [comment]
Check the pr now

**Pull request closed without merging**
