### PR TITLE
Created footer for about page

### PR DESCRIPTION
**Pull request by Sneha123-zudo**
#101 Added the footer to the about page , please review my pull request.

### CODE REVIEW

**Comment by Sneha123-zudo** [comment]
image

**Comment by Spandan-Bhattacharya** [comment]
It's good, but can you match the background of the footer as it is in the design, with the arrow-like structures.

**Comment by Sneha123-zudo** [comment]
Can you please explain, I can't able to understand

**Comment by Spandan-Bhattacharya** [comment]
footer-about
Make the footer like this, i mean the part below the white line, where currently the writing "made with passion at solve it" is present

**Comment by Sneha123-zudo** [comment]
I had a doubt , actually when i am opening the website by clicking on the link given in your project repository that background was not showing
image

**Comment by Spandan-Bhattacharya** [comment]
Yes it is not showing, i want you to implement the design in the background.

**Pull request closed without merging**
