### PR TITLE
Add new game ping pong game #296

### LINKED ISSUE #296: Add new game ping pong game
Add new game ping pong game

### PR DESCRIPTION
**Pull request by AftabMankapure**
Add new game ping pong game #296
issue #296 
close #296

### CODE REVIEW

**Comment by AftabMankapure** [comment]
@Spandan-Bhattacharya pls check this PR

**Comment by Spandan-Bhattacharya** [comment]
Change the colour scheme to match the other games.

**Comment by AftabMankapure** [comment]
@Spandan-Bhattacharya you need gradient background color ?

**Comment by Spandan-Bhattacharya** [comment]
Make the colour palette like that of the sudoku games.

**Comment by AftabMankapure** [comment]
new Ping
 
@Spandan-Bhattacharya  pls check this PR

**Pull request merged**
