### PR TITLE
Improved design of the 6x6 sudoku solver.

### PR DESCRIPTION
**Pull request by GhoshAditi**
issue #103 

@Spandan-Bhattacharya 
i have Improved the design of the 6x6 sudoku solver. i have made it on the same theme as of 4x4 sudoku solver as you have asked.

Screenshot :-
image

### CODE REVIEW

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya plz check

**Comment by Spandan-Bhattacharya** [comment]
Its good!
But the boxes are 3 in width and 2 in height.

And the background is not extending to the full screen.

**Comment by GhoshAditi** [comment]
> Its good! But the boxes are 3 in width and 2 in height.
> 
> And the background is not extending to the full screen. Also the font is a bit different than poppins i think

background is not extending to full screen? why? in my laptop it is totally fine.

**Comment by GhoshAditi** [comment]
> Its good! But the boxes are 3 in width and 2 in height.
> 
> And the background is not extending to the full screen. Also the font is a bit different than poppins i think

can you explain what you meant by boxes are 3 in width and 2 in height? did u ask me change their dimension into 3x2?

**Comment by Spandan-Bhattacharya** [comment]
Yes currently there are 4 3x3 boxes, the 6x6 sudoku has 6 3x2 boxes.

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya can u plz check whether the background is covering the whole page now or not?

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya can u plz check now? i think everything is fixed.

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya can u plz check?

**Comment by Spandan-Bhattacharya** [comment]
It looks great! Just one minor thing, the right side does not have the thicker blue border.
And the page does not have the poppins font.
Otherwise it's great!

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya I used the Poppins font only . U can check the code. Whenever I am using Poppins font that's what is coming . And for the right side border.....I will fix that tomorrow.....ok?

**Comment by Spandan-Bhattacharya** [comment]
Okay!

**Comment by GhoshAditi** [comment]
@Spandan-Bhattacharya i have added the right border. and have used the poppins font everywhere. plz check :)

**Comment by Spandan-Bhattacharya** [comment]
Good Job!

**Pull request merged**
