### PR TITLE
required changed done on hover effect of contributors page

### PR DESCRIPTION
**Pull request by thesri**
changed the color and link added to the name also in the contributors page. please check this jwoc 2024

### CODE REVIEW

**Comment by Spandan-Bhattacharya** [comment]
The links have lost their colour.

**Comment by thesri** [comment]
> The links have lost their colour.
> 
> And I think making the circles and the picture brighter would be better.

Okay give me an hour I will get back to you

**Comment by thesri** [comment]
@Spandan-Bhattacharya please check now

**Comment by Spandan-Bhattacharya** [comment]
Good Job!

**Pull request merged**
