### PR TITLE
Enhance the UI of the Tower of Hanoi solver. #191

### LINKED ISSUE #191: Enhance the UI of the Tower of Hanoi solver.
The Solver has a great animation, no need to change that.
Implement the following features:

- Add a back to home button
- Remove the New Game button: Implement it's functionality using only the 'number of discs' selector( When the user selects a number from the drop down, the user selected number of discs are reset to the left most column)
- The field where the steps are shown, make it so that it does not have scrollbar, i.e. if the number of steps is large, the field increases in length.
-  Make the UI of the page match the UI of the overall website in terms of fonts, colours and designs.

### PR DESCRIPTION
**Pull request by vishal2005025**
# closes #191

### CODE REVIEW

**Comment by vishal2005025** [comment]
Sir , please review and merge this issue..
Name : Vishal Malyan

**Comment by Spandan-Bhattacharya** [comment]
Sorry for the delay, can you make the background in some colour?

**Comment by Spandan-Bhattacharya** [comment]
@vishal2005025 any updates?

**Comment by vishal2005025** [comment]
Sorry, please give some time.
I will make changes till tomorrow..

**Comment by Spandan-Bhattacharya** [comment]
Okay!

**Comment by vishal2005025** [comment]
sir , please review and merge..

**Comment by Spandan-Bhattacharya** [comment]
Good Job!!

**Pull request merged**
